[menu]
profileButton = ":bust_in_silhouette:Profile"
languageButton = ":globe_with_meridians:Language"
receptionDeskButton = ":writing:Reception Desk"
backButton = ":arrow_left:Back"
resetStatsButton = ":book:Book of Obvilion"

[changeName]
changeNameWithoutName = "Enter the name separated by a space after the command: \"${name_command} Name\""
personageNameInvalidLength = """\
Sorry, but in the magic circle there is a restriction on the characters in the name. \
From ${min_name_length} to ${max_name_length} characters"""
personageNameInvalidSymbols = """
Unfortunately, in the magic circle to save the name, you can only use: \
cyrillic, latin, numbers characters _-.#№: and a space"""
successNameChange = "Name has been successfully changed!"

[leveling]
profileLevelUp = "You can improve your skills! Click ${level_up_command}"
notEnoughLevelingPoints = "You've reached your limit! If you want to change your fighting style, use the book of oblivion."
chooseLevelUpCharacteristic = "Choose what you want to learn next:"
successLevelUp = "Success level up:white_check_mark:"
successResetStats = """\
After reading the book, consciousness becomes clouded... You're forgetting your old skills. \
All paths are open to you again:"""
notEnoughMoney = "You can't afford the Book of Oblivion. You need ${money_icon}${money_count}"
