spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://localhost:5432/seeker"
    username: dev
    password: dev

ru.homyakin.seeker:
  telegram:
    token: "stub"
    username: "stub"