notEnoughUsers = """\
Күннің қызметкерін салтанатты түрде жариялау үшін қажетті адам саны: ${required_users}! \
Жай ғана жеке куәлігіңізді /me командасын жазып көрсетіңіз"""
alreadyChosen = [
    "Бүгінгі күннің үздік жұмыскері: ${mention_personage_badge_with_name}",
    "Бүгінгі күннің үздік жұмысшысы таңдалып қойылған, ол ${mention_personage_badge_with_name}, ертең келіңіз!"
]
chosenUser = [
    "Енді ${mention_personage_badge_with_name} Кресардың үздік жұмысшылар қатарына қосылды, міне, күрек, міне, молалар!",
    "Бүгінгі күннің үздік жұмыскері: ${mention_personage_badge_with_name}!",
]
