welcomeGroup = """\
Приветствую вас в таверне города Крезар, Искатели! \
Присаживайтесь за стол, заказывайте выпить, чувствуйте себя как дома
"""
chooseLanguage = "Выберите язык:"
onlyAdminLanguage = "Данное действие доступно только администраторам"
internalError = "Произошла ошибка, попробуйте позже"
help = """\
Социальная RPG в Telegram!
Просто добавь в чат и участвуй в событиях.
Официальный канал с новостями - ${news_channel_username}.

Доступные команды (в личке и в чате):
${language_command} - сменить язык;
${profile_command} - показать профиль;
${help_command} - данное сообщение;

Только для чата:
${duel_command} - вызвать другого искателя на дуэль. Должно быть ответом на сообщение другого пользователя;

Только для лички:
${name_command} - сменить имя;

Исходный код игры <a href="${github_link}">здесь</a>."""
profileTemplate = """\
${personage_icon}${personage_name}
${money_icon}Золото: ${personage_money}"""

# текста для группы
groupStats = """\
📊<b>Статистика группы:</b>

🗡Успешные рейды: ${raids_count}
🤺Завершено дуэлей: ${duels_count}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
"""

# текста для лички
# TODO перенести куда-нибудь
welcomeUser = "Добро пожаловать в таверну, Искатель!"
receptionDesk = "Здравствуйте! Чем могу помочь?"
mainMenu = [
    "Располагайся поудобнее, не торопись"
]
