welcomeGroup = """\
Приветствую вас в таверне города Крезар, Искатели! \
Присаживайтесь за стол, заказывайте выпить, чувствуйте себя как дома
"""
chooseLanguage = "Выберите язык:"
onlyAdminLanguage = "Данное действие доступно только администраторам"
internalError = "Произошла ошибка, попробуйте позже"
profileTemplate = """\
${personage_icon_with_name}
${money_icon}Золото: ${personage_money}
${energy_icon}Энергия: ${energy_value}%"""

# текста для группы
groupStats = """\
📊<b>Статистика группы:</b>

🗡Успешные рейды: ${raids_count}
🤺Завершено дуэлей: ${duels_count}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
"""
personageGroupStats = """\
📊<b>Твоя статистика в группе:</b>

🗡Успешные рейды: ${raids_success}/${raids_total}
🤺Победы в дуэлях: ${duels_wins}/${duels_total}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
⚒Работяга дня: ${spin_wins_count}
"""
personageBattleResult = "${personage_icon_with_name}: ${damage_dealt}💥 ${damage_taken}🛡 ${dodges_count}💨"
# текста для лички
# TODO перенести куда-нибудь
welcomeUser = "Добро пожаловать в таверну, Искатель!"
receptionDesk = "Здравствуйте! Чем могу помочь?"
mainMenu = [
    "Располагайся поудобнее, не торопись"
]
