duelMustBeReply = "Дуэль должна быть ответом на сообщение другого пользователя"
duelReplyMustBeToUser = "Вашим противником должен быть пользователь"
duelWithYourself = "Нельзя устроить дуэль с самим собой!"
duelWithInitiatorNotEnoughMoney = """\
Воу! Чтобы воспользоваться ареной тебе нужно хотя бы ${money_icon}${money_count}. Иди поработай для начала"""
duelWithAcceptorNotEnoughMoney = """\
Твой соперник не может себе позволить роскошь в виде арены за ${money_icon}${money_count}. \
Пусть сначала немного потрудится"""
personageAlreadyStartDuel = "Вы уже начали другую дуэль! Дождитесь ей окончания."
initDuel = """\
Искатель <b>${personage_icon}${initiating_personage_name}</b> вызывает на дуэль \
искателя <b>${personage_icon}${accepting_personage_name}</b>.

Каким будет его ответ?"""
notDuelAcceptingPersonage = "Это не вас вызвали на дуэль!"
expiredDuel = "Вызов на дуэль остался проигнорированным"
declinedDuel = "Принимающая сторона отклонила вызов!"
notEnoughMoneyAtAccepting = "Ты где-то умудрился потратить все деньги! Заработай для начала ${money_icon}${money_count}"
finishedDuel = """\
Искатель <b>${personage_icon}${winner_personage_name}</b> одержал верх над \
<b>${personage_icon}${looser_personage_name}</b>"""
acceptDuelButton = "Принять вызов:dagger_knife:"
declineDuelButton = "Отказаться :open_hands:"