duelMustBeReply = "Выбери себе противника для дуэли! Для этого нужно ответить на сообщение соперника."
duelWithDifferentBot = [
    "Выбери себе в противники кого-нибудь поживее!" # TODO здесь можно добавить рандомный пинг игрока
]
duelWithThisBot = [
    "Не советую начинать драку с персоналом! Иначе в твоём пиве может оказаться специальная пенка от официанта"
]
duelWithYourself = "Нельзя устроить дуэль с самим собой!"
duelWithInitiatorNotEnoughMoney = [
    "Воу! Чтобы воспользоваться ареной тебе нужно хотя бы ${money_icon}${money_count}. Иди поработай для начала",
    "Вход в арену стоит ${money_icon}${money_count}, иди работать!",
    "Бой - привелегия богатых, а не бедных. Накопи ${money_icon}${money_count} и возвращайся.",
    "Кажется, этот бой тебе не по карману! Необходимо ${money_icon}${money_count}."
]
personageAlreadyStartDuel = "Вы уже начали другую дуэль! Дождитесь ей окончания."
initDuel = [
    """\
Искатель <b>${initiating_personage_icon_with_name}</b> вызывает на дуэль \
искателя <b>${accepting_personage_icon_with_name}</b>.

Каким будет его ответ?""",
    """\
От <b>${initiating_personage_icon_with_name}</b> прилетела перчатка в лицо \
<b>${accepting_personage_icon_with_name}</b>!""",
    "Возми себя в руки, <b>${accepting_personage_icon_with_name}</b>, и прими вызов от <b>${initiating_personage_icon_with_name}</b>!",
    "<b>${initiating_personage_icon_with_name}</b> явно намеревается дать по щам <b>${accepting_personage_icon_with_name}</b>!"
]
notDuelAcceptingPersonage = "Это не вас вызвали на дуэль!"
expiredDuel = [
    "Вызов на дуэль остался проигнорированным",
    "<b>${accepting_personage_icon_with_name}</b>: Хочу иду на дуэль, хочу не иду, мне вообще пофиг!",
    "<b>${accepting_personage_icon_with_name}</b> не может выйти на дуэль. Позовите позднее.",
    "<b>${accepting_personage_icon_with_name}</b> наказала мама. Пока полы не будут помыты - дуэли не будет!"
]
declinedDuel = [
    "Принимающая сторона отклонила вызов!",
    "Ха! <b>${initiating_personage_icon_with_name}</b>, ищи дурака для дуэли в другом месте!"
]
finishedDuel = [
    """\
Искатель <b>${winner_personage_icon_with_name}</b> одержал верх над \
<b>${looser_personage_icon_with_name}</b>""",
    "<b>${looser_personage_icon_with_name}</b> размазали тонким слоем по брущатке!",
    "Бой окончен! <b>${winner_personage_icon_with_name}</b> явно сильнее <b>${looser_personage_icon_with_name}</b>!",
    "Во время дуэли <b>${winner_personage_icon_with_name}</b> легким движением руки отправляет спать <b>${looser_personage_icon_with_name}</b>!",
    "В следующий раз <b>${looser_personage_icon_with_name}</b> подумает дважды, прежде чем драться с <b>${winner_personage_icon_with_name}</b>."
]
acceptDuelButton = "Принять вызов:dagger_knife:"
declineDuelButton = "Отказаться :open_hands:"
