notEnoughUsers = """\
Для торжественного объявления Работяги дня необходимо собрать хотя бы минимальную группу: ${required_users}! \
Просто покажите удостоверение через /me"""
alreadyChosen = [
    "На сегодня место главного работяги занято ${personage_icon_with_name}",
    "Все работяги уже распределены. Сегодня это ${personage_icon_with_name}. Приходите завтра!"
]
chosenUser = [
    "Теперь ${personage_icon_with_name} в рядах работяг Крезара, вот лопата, вот могилы! +${money_count}${money_icon}",
    "Работяга дня - ${personage_icon_with_name}! Занимается отшкребыванием зубастых грибов у бабы Зины на даче. +${money_count}${money_icon}",
    """\
Добро пожаловать в ряды работяг, ${personage_icon_with_name}! \
Туалеты тут, вилку в зубы и вот так вот раз-раз, раз-раз! +${money_count}${money_icon}""",
    """\
Новая задача для работяги! Как известно волк в цирке не выступает, \
а ${personage_icon_with_name} с удовольствием заменит его сегодня на арене! +${money_count}${money_icon}""",
    """\
Барды всю ночь драли глотки. Сегодня работяге ${personage_icon_with_name} \
предстоит смазать все гортани музыкантов для дальнейшей эксплуатации. +${money_count}${money_icon}""",
    """\
Работа не волк, да и ${personage_icon_with_name не волк. \
Просто настоящий работяга — давайте хотя бы сегодня это признаем! +${money_count}${money_icon}""",

]
noChosenUsers = "Никто ещё не был назначен работягой в этой группе."
topChosenUsers = "Топ работяг за всё время:"
