main = """\
Добро пожаловать в таверну города Крезар!

Здесь ты можешь отдохнуть, выпить или доказать, что кто-то не прав, вызвав его на дуэль. \
Также можно заработать немного золота в рейдах.

Не стесняйся обращаться за помощью, мы с радостью тебе поможем.
"""

raids = """\
Для того, чтобы участвовать в рейдах, необходимо добавить бота в свою группу.
После этого через определённые промежутки времени в таверне будут появляться объявления, \
за участие в которых можно заработать денег. Если рейд завершится успехом, то и награда возрастёт.

И помните! Чем больше искателей, тем больше шансов на победу!
"""

duels = """\
Если тебе кажется, что в таверне кто-то не прав, то за таверной есть специальная арена для выяснения отношений!
Просто ответь на сообщение обидчика с помощью ${duel_command}.

Однако знай, что арена — это не бесплатное удовольствие! Кто-то же должен отмыть её потом от крови и убрать выбитые зубы.
"""

menu = """\
Как и в любой уважающей себя таверне, у нас можно выпить и вкусно покушать.

Ознакомься со списком доступных позиций через ${menu_command} и заказывай то, что тебе понравилось!
"""

personage = """\
Перейдя в ${bot_username}, ты можешь воспользоваться стойкой регистрации.

Там ты сможешь сменить своё имя с помощью магического круга.
Или можешь заплатить за доступ к книге забвения, чтобы забыть свои боевые навыки и выучить новые.
"""

info = """\
Новости проекта можно найти на этом канале: ${news_channel_username}.

Исходный код игры находится <a href="${source_code_link}">здесь</a>.
Также по этой ссылке можно найти, как помочь переводу контента на другие языки.
"""


raidsButton = "🗡Рейды"
duelsButton = "🤺Дуэли"
menuButton = "🍻Таверна"
personageButton = "🔰Искатель"
infoButton = "💬Прочее"

