[menu]
profileButton = ":bust_in_silhouette:Профиль"
languageButton = ":globe_with_meridians:Язык"
receptionDeskButton = ":writing:Стойка регистрации"
backButton = ":arrow_left:Назад"
resetStatsButton = ":book:Книга забвения"

[changeName]
changeNameWithoutName="Введите имя через пробел после команды: \"${name_command} Имя\""
personageNameInvalidLength = """\
Прости, но в магическом круге есть ограничение на символы в имени. От ${min_name_length} до ${max_name_length} символов"""
personageNameInvalidSymbols = """\
К сожалению, в магическом круге для сохранения имени можно использовать только: \
кириллицу, латиницу, цифры, символы _-.#№ и пробел"""
successNameChange = "Имя успешно изменено!"

[leveling]
profileLevelUp = "Ты можешь улучшить свои навыки! Жми ${level_up_command}"
notEnoughLevelingPoints = "Ты достиг своего предела! Если хочешь изменить стиль боя, воспользуйся книгой забвения."
chooseLevelUpCharacteristic = "Выбери, чему ты хочешь обучиться дальше:"
successLevelUp = "Навык успешно улучшен:white_check_mark:"
successResetStats = """\
После прочтения книги сознание затуманивается... Ты забываешь свои старые навыки. Перед тобой снова открыты все пути:"""
notEnoughMoney = "Книга забвения тебе не по карману! Нужно ${money_icon}${money_count}"
