[menu]
profileButton = ":bust_in_silhouette:Профиль"
languageButton = ":globe_with_meridians:Язык"
receptionDeskButton = ":writing:Стойка регистрации"
backButton = ":arrow_left:Назад"
resetCharacteristicsButton = ":book:Книга забвения"

[changeName]
changeNameWithoutName="Введите имя через пробел после команды: \"${name_command} Имя\""
personageNameInvalidLength = """\
Прости, но в магическом круге есть ограничение на символы в имени. От ${min_name_length} до ${max_name_length} символов"""
personageNameInvalidSymbols = """\
К сожалению, в магическом круге для сохранения имени можно использовать только: \
кириллицу, латиницу, цифры, символы _-.#№ и пробел"""
successNameChange = "Имя успешно изменено!"

[characteristics]
resetConfirmation = """\
Для того, чтобы прочесть книгу забвения необходимо заплатить ${money_icon}${money_count}. \
Ты точно хочешь забыть свои старые навыки?"""
successReset = """\
После прочтения книги сознание затуманивается... Ты забываешь свои старые навыки. Перед тобой снова открыты все пути."""
canceledReset = "Книга останется здесь. Приходи, когда решишься"
increasedCharacteristic = "Ты улучшил навык: ${increased_value}${increased_icon}."
currentCharacteristics = """\
Текущие характеристики: ${strength_value}${strength_icon}${agility_value}${agility_icon}${wisdom_value}${wisdom_icon}"""
chooseCharacteristic = "Выбери, что ты хочешь изучить:"
notEnoughCharacteristicPoints = "Ты достиг своего предела! Если захочешь изменить стиль боя, воспользуйся книгой забвения."
notEnoughMoney = "Книга забвения тебе не по карману! Нужно ${money_icon}${money_count}"
profileLevelUp = "Ты можешь улучшить свои навыки! Жми ${level_up_command}"
confirmButton = "📖Прочесть"
cancelButton = "❌В другой раз"
strengthButton = "+1${strength_icon}"
agilityButton = "+1${agility_icon}"
wisdomButton = "+1${wisdom_icon}"
