joinRaidEvent = "Присоединиться к рейду:dagger_knife:"
raidStartsPrefix = "Битва начнётся через"
hoursShort = "ч."
minutesShort = "мин."
successJoinEvent = "Вы успешно присоединились к событию!"
userAlreadyInThisEvent = "Вы уже участвуете в данном событии!"
userAlreadyInOtherEvent = "Вы уже участвуете в другом событии!"
expiredRaid = "Рейд завершён!"
successRaid = [
    "Событие завершилось! Рейд был успешен.",
    "Эпичный был бой! Вы преуспели, вот ваша награда!",
    "Противники повержены! А вы, оказывается, не сопляки!"
]
failureRaid = [
    "Искатели провалили рейд. За что мы вам деньги платим?",
    "Эх, провал. Может, стоит собрать больше искателей?",
    "Бой был не самым успешным. Теперь вы по уши в дерьме."
]
