joinRaidEvent = "Присоединиться к рейду🗡"
raidStartsPrefix = "Битва начнётся через"
hoursShort = "ч."
minutesShort = "мин."
userAlreadyInThisEvent = "Вы уже участвуете в данном событии!"
userAlreadyInOtherEvent = "Вы уже участвуете в другом событии!"
expiredRaid = "Рейд завершён!"
raidInProcess = "Рейд уже начался"
successRaid = [
    "Событие завершилось! Рейд был успешен.",
    "Эпичный был бой! Вы преуспели, вот ваша награда!",
    "Противники повержены! А вы, оказывается, не сопляки!"
]
failureRaid = [
    "Искатели провалили рейд. За что мы вам деньги платим?",
    "Эх, провал. Может, стоит собрать больше искателей?",
    "Бой был не самым успешным. Теперь вы по уши в дерьме."
]
zeroParticipants = [
    "Никто не принял заказ😢В этот раз денег никто не получит."
]
personageRaidResult = "${dead_icon_or_empty}${personage_icon_with_name}: ${damage_dealt}💥 ${damage_taken}🛡 +${money}${money_icon}"
raidResult = """\
Противники: ${remain_enemies_health}/${total_enemies_health}❤️ ${remain_enemies_count}/${total_enemies_count}👹

Лучшие искатели:
${top_personages_list}"""
raidParticipants = "Участники: ${personage_icon_name_list}"
notEnoughEnergy = "Выглядишь уставшим! Отдохни хотя бы до ${energy_icon}${required_energy}%"
