joinRaidEvent = "Присоединиться к рейду🗡"
raidStartsPrefix = "Битва начнётся через"
hoursShort = "ч."
minutesShort = "мин."
successJoinEvent = "Вы успешно присоединились к событию!"
userAlreadyInThisEvent = "Вы уже участвуете в данном событии!"
userAlreadyInOtherEvent = "Вы уже участвуете в другом событии!"
expiredRaid = "Рейд завершён!"
raidInProcess = "Рейд уже начался"
successRaid = [
    "Событие завершилось! Рейд был успешен.",
    "Эпичный был бой! Вы преуспели, вот ваша награда!",
    "Противники повержены! А вы, оказывается, не сопляки!"
]
failureRaid = [
    "Искатели провалили рейд. За что мы вам деньги платим?",
    "Эх, провал. Может, стоит собрать больше искателей?",
    "Бой был не самым успешным. Теперь вы по уши в дерьме."
]
zeroParticipants = [
    "Никто не принял заказ😢В этот раз денег никто не получит."
]
raidResult = """\
Противники: ${remain_enemies_health}/${total_enemies_health}❤️ ${remain_enemies_count}/${total_enemies_count}👹

Лучшие искатели:
${top_personages_list}"""
