topRaidWeek = """\
🏆Топ всех Искателей в рейдах за неделю <code>${start_date} - ${end_date}</code>:

${top_personage_list}

Всего участников: ${total_count}"""
topRaidWeekGroup = """\
🏆Топ Искателей в группе в рейдах за неделю <code>${start_date} - ${end_date}</code>:

${top_personage_list}

Всего участников: ${total_count}"""
topRaidPosition = "${position}. ${personage_badge_with_name} ${success_raids}/${all_raids}"
topRaidEmpty = "Никто не участвовал в рейдах за выбранный период"
topList = """\
📊Список топов доступных к просмотру:

⚒Топ работяг в группе ${top_work_group_command}

🗡Топ Искателей в рейдах за неделю ${top_raid_week_command}
🗡Топ Искателей группы в рейдах за неделю ${top_raid_week_group_command}"""