triggerCreated = "Никто не участвовал в рейдах за выбранный период"
triggerNotFound = "Триггер не найден"
triggerDeleted = "Триггер успешно удалён"
noTriggerText = "Нет текста для создания триггера"
unknownException = "Неизвестная ошибка работы с триггерами"